[package]
name = "rpg"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt.level = 3
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.6"}
bevy-inspector-egui = "0.8"
benimator = "2.2.0"
